sudo: required
services:
    - docker
before_install:
    - docker build -t bhagath/frontend -f Dockerfile.dev .
script:
    - docker run -e CI=true bhagath/frontend npm run test
language: generic

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "DOCKER-APP"
    env: "DockerApp-env"
    bucket_name: "elasticbeanstalk-ap-south-1-167500560729"
    bucket_path: "DOCKER-APP"
    on:
        branch: master